// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqzSCPx2bRfuNZ8qbrQLoX1zsMfG0cFho',
    appId: '1:508637029414:web:9b8b815e290e43b75ef2e7',
    messagingSenderId: '508637029414',
    projectId: 'crafty-raceway-356813',
    authDomain: 'crafty-raceway-356813.firebaseapp.com',
    storageBucket: 'crafty-raceway-356813.appspot.com',
    measurementId: 'G-GHM0MZPW4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ukf4a9F7o_O8ms4AwMyAz0OhK3VAR-I',
    appId: '1:508637029414:android:480a07cbd40e5c875ef2e7',
    messagingSenderId: '508637029414',
    projectId: 'crafty-raceway-356813',
    storageBucket: 'crafty-raceway-356813.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy0RyAC37PtW_FaxIFkDsXhBZHflQLTsQ',
    appId: '1:508637029414:ios:f2f586b7738f879b5ef2e7',
    messagingSenderId: '508637029414',
    projectId: 'crafty-raceway-356813',
    storageBucket: 'crafty-raceway-356813.appspot.com',
    iosBundleId: 'com.example.rfidStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy0RyAC37PtW_FaxIFkDsXhBZHflQLTsQ',
    appId: '1:508637029414:ios:bef2627c5b6a2daa5ef2e7',
    messagingSenderId: '508637029414',
    projectId: 'crafty-raceway-356813',
    storageBucket: 'crafty-raceway-356813.appspot.com',
    iosBundleId: 'com.example.rfidStore.RunnerTests',
  );

}

